[package]
name = "ribus"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glib-sys.workspace = true
gobject-sys.workspace = true
tracing.workspace = true

[lints]
workspace = true
