[package]
name = "gokien"
version = "0.1.0"
edition = "2021"

[dependencies]
scopeguard = "1.2.0"
vi = "0.5.1"

[dependencies.xcb]
version = "1.3.0"
features = [
	# "xlib_xcb",
	# "xinput",
	# "xkb",
]

# [dependencies.x11]
# version = "2.21"
# features = [
# 	"xlib",
# ]
